on:
  push:
    branches:
      - main
  pull_request:

name: pipeline
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  dotnet-version: |
    9.0.x

jobs:
  build:
    name: validate solutions
    runs-on: ubuntu-latest
    steps:
      # Setup
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.dotnet-version }}

      - run: dotnet --info

      # Checkout
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # Test
      - run: dotnet test -c Release
